name: Build Masscan Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-gcc

      - name: Build
        shell: msys2 {0}
        run: |
          make

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: masscan-windows
          path: bin/masscan.exe
